# Generated by Django 4.2.9 on 2024-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan2',
            name='gambar',
            field=models.ImageField(upload_to='webku/static'),
        ),
    ]
