# Generated by Django 4.2.9 on 2024-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0002_alter_makanan2_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='gambar',
            field=models.ImageField(upload_to='webku/static'),
        ),
    ]
