# Generated by Django 4.2.9 on 2024-12-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0003_alter_makanan_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='makanan',
            name='gambar',
            field=models.ImageField(upload_to='makanan_images/'),
        ),
        migrations.AlterField(
            model_name='makanan2',
            name='category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Maccarone', 'Maccarone'), ('Cookies', 'Cookies'), ('Short Cake', 'Short Cake')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='makanan2',
            name='gambar',
            field=models.ImageField(upload_to='category_makanan/'),
        ),
    ]
