# Generated by Django 4.2.9 on 2024-12-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='makanan',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
