# Generated by Django 4.2.9 on 2024-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0005_profile_balance_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance_requested',
            field=models.BooleanField(default=False),
        ),
    ]
