# Generated by Django 4.2.9 on 2024-12-19 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0006_client_balance_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance_requested',
        ),
        migrations.RemoveField(
            model_name='client',
            name='saldo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='+62 000000000', max_length=15),
        ),
    ]
