# Generated by Django 4.2.9 on 2024-12-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0010_topuprequest_is_deleted_alter_topuprequest_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topuprequest',
            old_name='is_deleted',
            new_name='is_approved',
        ),
    ]
