# Generated by Django 4.2.9 on 2024-12-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0011_rename_is_deleted_topuprequest_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuprequest',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
