# Generated by Django 4.2.9 on 2024-12-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0012_remove_topuprequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='makanan2',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
