# Generated by Django 4.2.9 on 2024-12-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0014_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
