# Generated by Django 4.2.9 on 2024-12-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0017_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tanggal',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
